import { StyleSheet } from 'react-native';

export const budgetStyles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingTop: 60, paddingBottom: 16, paddingHorizontal: 20, borderBottomWidth: 0.5 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { fontSize: 28, fontWeight: '700', letterSpacing: -0.5 },
  infoBtn: { padding: 4 },
  monthNav: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 12 },
  monthArrow: { padding: 4 },
  monthText: { fontSize: 15, fontWeight: '500' },
  scrollContent: { padding: 20, paddingBottom: 100 },
  overviewCard: { borderRadius: 16, padding: 18, marginBottom: 20, borderWidth: 1 },
  overviewRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14 },
  overviewItem: {},
  overviewLabel: { fontSize: 11, marginBottom: 3 },
  overviewVal: { fontSize: 15, fontWeight: '700' },
  progressTrack: { height: 6, borderRadius: 3, overflow: 'hidden', marginBottom: 6 },
  progressFill: { height: '100%', borderRadius: 3 },
  progressLabel: { fontSize: 11, textAlign: 'right' },
  budgetItem: { paddingVertical: 16, borderBottomWidth: 0.5 },
  budgetTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  budgetLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  budgetName: { fontSize: 15, fontWeight: '500' },
  budgetTopRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  budgetPercent: { fontSize: 14, fontWeight: '700' },
  deleteBtn: { padding: 4, marginTop: -2 },
  budgetBottom: { flexDirection: 'row', alignItems: 'baseline', gap: 4, marginTop: 4 },
  emptyWrap: { alignItems: 'center', paddingTop: 80 },
  emptyText: { fontSize: 16, fontWeight: '500' },
  fab: { position: 'absolute', bottom: 90, right: 20, width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 8 },
  fabText: { fontSize: 28, color: '#fff', fontWeight: '300', marginTop: -1 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  modal: { borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 40, maxHeight: '85%' },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: '#D0D0D0', alignSelf: 'center', marginBottom: 12 },
  modalHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: '700' },
  amtRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  amtPrefix: { fontSize: 28, fontWeight: '700', marginRight: 6 },
  amtInput: { flex: 1, fontSize: 32, fontWeight: '700' },
  descInput: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, marginBottom: 16 },
  sectionLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 10 },
  dateBtn: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 16 },
  monthPickerWrap: { borderWidth: 1, borderRadius: 16, padding: 12, marginBottom: 16, marginTop: -8 },
  yearNav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, paddingHorizontal: 4 },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  monthCell: { width: '25%', paddingVertical: 12, alignItems: 'center' },
  monthCellText: { fontSize: 13, fontWeight: '500' },
  catHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  catGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  catChip: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, gap: 6 },
  catName: { fontSize: 13, fontWeight: '500' },
  submitBtn: { paddingVertical: 16, borderRadius: 14, alignItems: 'center', marginTop: 4 },
  submitText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  catModalWrap: { margin: 20, borderRadius: 20, padding: 20, marginTop: 'auto', marginBottom: 'auto' },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  iconBtn: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  catModalBtns: { flexDirection: 'row', gap: 10 },
  catModalBtn: { flex: 1, paddingVertical: 14, borderRadius: 12, alignItems: 'center', borderWidth: 1 },
});
