import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingTop: 60, paddingBottom: 16, paddingHorizontal: 20, borderBottomWidth: 0.5 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { fontSize: 28, fontWeight: '700', letterSpacing: -0.5 },
  infoBtn: { padding: 4 },
  scrollContent: { padding: 20, paddingBottom: 100 },
  profileCard: { alignItems: 'center', padding: 30, borderRadius: 16, marginBottom: 20, borderWidth: 1 },
  avatar: { width: 80, height: 80, borderRadius: 40, justifyContent: 'center', alignItems: 'center' },
  avatarText: { fontSize: 32, fontWeight: '700' },
  avatarWrap: { width: 80, height: 80, marginBottom: 16, position: 'relative' },
  avatarImage: { width: 80, height: 80, borderRadius: 40 },
  avatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  userName: { fontSize: 20, fontWeight: '600', marginBottom: 4 },
  userEmail: { fontSize: 14 },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 30 },
  statCard: { flex: 1, padding: 16, borderRadius: 16, alignItems: 'center', borderWidth: 1 },
  statIcon: { fontSize: 20, marginBottom: 8 },
  statLabel: { fontSize: 11, marginBottom: 4, textAlign: 'center', fontWeight: '500' },
  statValue: { fontSize: 14, fontWeight: '700', textAlign: 'center' },
  sectionTitle: { fontSize: 13, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 10, marginLeft: 4 },
  settingsCard: { borderRadius: 16, marginBottom: 30, borderWidth: 1 },
  settingItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  settingLeft: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  settingIconBg: { width: 36, height: 36, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  settingIcon: { fontSize: 16 },
  settingLabel: { fontSize: 15, fontWeight: '500' },
  dividerLine: { height: 0.5, marginLeft: 62 },
  logoutBtn: { padding: 16, borderRadius: 14, alignItems: 'center', borderWidth: 1 },
  logoutText: { fontSize: 15, fontWeight: '600' },
  version: { textAlign: 'center', fontSize: 12, marginTop: 24 },
  
  /* Edit modal */
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  editModal: {
    width: '100%',
    borderRadius: 24,
    padding: 24,
  },
  editModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 20,
  },
  editInput: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    fontSize: 16,
    marginBottom: 20,
  },
  editModalActions: {
    flexDirection: 'row',
    gap: 12,
  },
  editBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
  },
});
