import { StyleSheet } from 'react-native';

export const statisticsStyles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingTop: 60, paddingBottom: 16, paddingHorizontal: 20, borderBottomWidth: 0.5 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { fontSize: 28, fontWeight: '700', letterSpacing: -0.5 },
  infoBtn: { padding: 4 },
  monthNav: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 12 },
  monthArrow: { padding: 4 },
  monthText: { fontSize: 15, fontWeight: '500' },
  scrollContent: { padding: 20, paddingBottom: 100 },
  summaryRow: { flexDirection: 'row', gap: 12, marginBottom: 20 },
  summaryCard: { flex: 1, padding: 16, borderRadius: 16, borderWidth: 1 },
  iconBg: { width: 40, height: 40, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  summaryIcon: { fontSize: 20 },
  summaryLabel: { fontSize: 13, marginBottom: 4, fontWeight: '500' },
  summaryValue: { fontSize: 18, fontWeight: '700' },
  savingsCard: { padding: 20, borderRadius: 16, marginBottom: 24, borderWidth: 1 },
  goalCard: { padding: 20, borderRadius: 16, marginBottom: 24, borderWidth: 1 },
  goalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  goalTitle: { fontSize: 16, fontWeight: '700' },
  savingsTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 },
  savingsLabel: { fontSize: 13, marginBottom: 4, fontWeight: '500' },
  savingsAmount: { fontSize: 28, fontWeight: '800', letterSpacing: -0.5 },
  savingsRateText: { fontSize: 16, fontWeight: '700', marginTop: 4 },
  progressBar: { height: 6, borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 3 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  sectionTitle: { fontSize: 18, fontWeight: '700' },
  typeToggle: { flexDirection: 'row', borderRadius: 8, borderWidth: 1, overflow: 'hidden' },
  typeBtn: { paddingHorizontal: 12, paddingVertical: 6 },
  typeText: { fontSize: 12, fontWeight: '600' },
  chartCard: { borderRadius: 16, padding: 20, marginBottom: 24, borderWidth: 1 },
  donutRing: { flexDirection: 'row', height: 8, borderRadius: 4, overflow: 'hidden', width: '100%', marginBottom: 20 },
  donutSegment: { height: '100%' },
  catItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14 },
  catLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  catDot: { width: 10, height: 10, borderRadius: 5 },
  catName: { fontSize: 14, fontWeight: '500' },
  catRight: { alignItems: 'flex-end' },
  catAmount: { fontSize: 14, fontWeight: '600' },
  catPercent: { fontSize: 12, marginTop: 2 },
  trendCard: { borderRadius: 16, padding: 20, marginBottom: 24, borderWidth: 1 },
  barChart: { flexDirection: 'row', alignItems: 'flex-end', height: 110, gap: 4 },
  barGroup: { alignItems: 'center', width: 28 },
  barContainer: { height: 80, justifyContent: 'flex-end' },
  barDualWrap: { flexDirection: 'row', gap: 2, alignItems: 'flex-end' },
  bar: { width: 10, borderRadius: 3 },
  barLabel: { fontSize: 10, marginTop: 6, fontWeight: '500' },
  legendRow: { flexDirection: 'row', justifyContent: 'center', gap: 16, marginTop: 16, borderTopWidth: 0.5, borderColor: '#ccc', paddingTop: 12 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { fontSize: 12, color: '#888' },
  emptyCard: { borderRadius: 16, padding: 30, alignItems: 'center', marginBottom: 24, borderWidth: 1 },
  emptyText: { fontSize: 14, fontWeight: '500' },
  modalOverlay: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: 'rgba(0,0,0,0.35)' },
  goalModal: { borderRadius: 16, padding: 16 },
  modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },
  modalInput: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 10 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 8 },
  modalBtn: { flex: 1, borderWidth: 1, borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
});
